const schemas = ["asset.json",
    "attack-pattern.json",
    "campaign.json",
    "core.json",
    "course-of-action.json",
    "identity.json",
    "indicator.json",
    "infrastructure.json",
    "intrusion-set.json",
    "kill-chain-phase.json",
    "malware.json",
    "marking-definition.json",
    "observed-data.json",
    "relationship.json",
    "report.json",
    "sighting.json",
    "threat-actor.json",
    "timestamp.json",
    "tool.json",
    "vulnerability.json",
    "common/bundle.json",
    "common/core.json",
    "common/cyber-observable-core.json",
    "common/dictionary.json",
    "common/external-reference.json",
    "common/granular-marking.json",
    "common/hashes-type.json",
    "common/hex.json",
    "common/identifier.json",
    "common/kill-chain-phase.json",
    "common/marking-definition.json",
    "common/timestamp.json",
    "common/url-regex.json",
    "observables/artifact.json",
    "observables/autonomous-system.json",
    "observables/directory.json",
    "observables/domain-name.json",
    "observables/email-addr.json",
    "observables/email-message.json",
    "observables/file.json",
    "observables/ipv4-addr.json",
    "observables/ipv6-addr.json",
    "observables/mac-addr.json",
    "observables/mutex.json",
    "observables/network-traffic.json",
    "observables/process.json",
    "observables/software.json",
    "observables/url.json",
    "observables/user-account.json",
    "observables/windows-registry-key.json",
    "observables/x509-certificate.json",
];
export const schema_map = {};
for (const schema of schemas) {
    // tslint:disable-next-line:no-var-requires
    schema_map[schema] = require(`../static/jsedit/${schema}`);
    schema_map[`static/jsedit/${schema}`] = schema_map[schema];
}
