# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='stix_loader',
    version='0.0.0',
    python_requires='==3.7.7',
    packages=[
        'stix_loader', 'stix_loader.models', 'stix_loader.models.v20',
        'stix_loader.models.v21'
    ],
    package_dir={"": "."},
    install_requires=[
        'appdirs', 'dateparser', 'decorator', 'ipython', 'ipython-genutils',
        'jedi', 'pexpect', 'pickleshare', 'prompt-toolkit', 'ptyprocess',
        'pygments', 'pyorient', 'pyparsing', 'python-dateutil', 'pytz', 'regex',
        'simplegeneric', 'six', 'stix2', 'taxii2-client', 'tqdm', 'traitlets',
        'tzlocal', 'wcwidth'
    ],
    extras_require={"dev": ["ipykernel", "pipdeptree", "pipgrip", "pylint"]},
)
